# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDenemecase():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_denemecase(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1382, 744)
    element = self.driver.find_element(By.LINK_TEXT, "Neler Sunuyoruz?")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//input[@name=\'email\']").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//input[@name=\'email\']")))
    self.driver.find_element(By.XPATH, "//input[@name=\'email\']").send_keys("sinemarslantr@gmail.com")
    self.driver.find_element(By.XPATH, "//input[@name=\'password\']").click()
    WebDriverWait(self.driver, 0.5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//input[@name=\'password\']")))
    self.driver.find_element(By.XPATH, "//input[@name=\'password\']").click()
    self.driver.find_element(By.XPATH, "//input[@name=\'password\']").send_keys("r4jS2QvfZpn8fZd")
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div/div/form/button").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id=\'__next\']/div/div[2]/div/div")))
    assert self.driver.find_element(By.XPATH, "//*[@id=\"__next\"]/div/div[2]/div/div[2]").text == "• Giriş başarılı."
  
