# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from time import sleep

class TestTestcase3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testcase3(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Giriş Yap\')]").click()
    assert self.driver.find_element(By.XPATH, "//*[@id=\"__next\"]/div/main/section/div/div/div/div/form/p[1]").text == "Doldurulması zorunlu alan*"
    assert self.driver.find_element(By.XPATH, "//*[@id=\"__next\"]/div/main/section/div/div/div/div/form/p[2]").text == "Doldurulması zorunlu alan*"
    sleep(3)
  
